import { NavLink, Routes, Route, useNavigate } from "react-router-dom";
import { LayoutDashboard, Film, Tv, Users, CreditCard, FileText, BarChart3, Settings, Plus, Eye, Clock3 } from "lucide-react";
import { movies, shows, blogs } from "../data";
import { Section, Button } from "../components/UI";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, BarChart, Bar } from "recharts";
const data=[{day:"Mon",views:4200,users:1200},{day:"Tue",views:6100,users:1500},{day:"Wed",views:5200,users:1400},{day:"Thu",views:7800,users:1900},{day:"Fri",views:9100,users:2300},{day:"Sat",views:11200,users:2800},{day:"Sun",views:9800,users:2500}];
export function Admin(){return <div className="mx-auto flex max-w-[1500px] gap-5 px-4 py-6 lg:px-8"><aside className="hidden w-56 shrink-0 rounded-2xl border border-white/10 bg-panel p-3 md:block"><div className="px-3 py-4 text-lg font-black">Admin<span className="text-violet-300">.</span></div>{[["/admin/dashboard","Dashboard",LayoutDashboard],["/admin/movies","Movies",Film],["/admin/shows","Shows",Tv],["/admin/users","Users",Users],["/admin/subscriptions","Subscriptions",CreditCard],["/admin/blogs","Blogs",FileText],["/admin/analytics","Analytics",BarChart3],["/admin/settings","Settings",Settings]].map(([to,l,I]:any)=><NavLink key={to} to={to} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/50 hover:bg-white/5 hover:text-white"><I size={16}/>{l}</NavLink>)}</aside><div className="min-w-0 flex-1"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/movies" element={<Content title="Movies" count={movies.length}/>}/><Route path="/shows" element={<Content title="TV Shows" count={shows.length}/>}/><Route path="/users" element={<Content title="Users" count={12840}/>}/><Route path="/subscriptions" element={<Content title="Subscriptions" count={3240}/>}/><Route path="/blogs" element={<Content title="Blog Posts" count={blogs.length}/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/settings" element={<Content title="Admin Settings" count={0}/>}/></Routes></div></div>}
function Dashboard(){return <Section title="Dashboard" subtitle="StreamVerse platform overview"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["12,840","Total users"],["3,240","Subscribers"],["52","Movies"],["84.2K","Watch hours"]].map(([a,b],i)=><div key={b} className="rounded-2xl border border-white/10 bg-panel p-5"><div className="text-3xl font-black">{a}</div><div className="mt-1 text-sm text-white/40">{b}</div><div className="mt-4 text-xs text-cyan-300">+{i+4}.8% this month</div></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-white/10 bg-panel p-5"><div className="mb-5 font-bold">Views & active users</div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><XAxis dataKey="day" stroke="#666" /><YAxis stroke="#666"/><Tooltip contentStyle={{background:"#11131b",border:"1px solid #333"}}/><Area type="monotone" dataKey="views" stroke="#a78bfa" fill="#a78bfa" fillOpacity={.12}/><Area type="monotone" dataKey="users" stroke="#67e8f9" fill="#67e8f9" fillOpacity={.08}/></AreaChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-white/10 bg-panel p-5"><div className="mb-5 font-bold">Popular genres</div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{g:"Sci-Fi",v:88},{g:"Action",v:75},{g:"Drama",v:62},{g:"Anime",v:91},{g:"Comedy",v:48}]}><XAxis dataKey="g" stroke="#666"/><YAxis stroke="#666"/><Tooltip contentStyle={{background:"#11131b",border:"1px solid #333"}}/><Bar dataKey="v" fill="#a78bfa" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></div></Section>}
function Content({title,count}:{title:string;count:number}){return <Section title={title} subtitle={`${count} records`} action={<Button><Plus size={15}/> Add new</Button>}><div className="overflow-hidden rounded-2xl border border-white/10 bg-panel"><div className="grid grid-cols-4 border-b border-white/10 px-5 py-3 text-xs uppercase tracking-wider text-white/35"><span>Title</span><span>Status</span><span>Views</span><span>Updated</span></div>{Array.from({length:8},(_,i)=><div key={i} className="grid grid-cols-4 items-center border-b border-white/5 px-5 py-4 text-sm"><span className="font-semibold">{title} Item {i+1}</span><span className="text-cyan-300">Published</span><span>{(i+2)*1840}</span><span className="text-white/40">{i+1}h ago</span></div>)}</div></Section>}
function Analytics(){return <Section title="Analytics" subtitle="Content performance and audience insights"><div className="grid gap-4 sm:grid-cols-3">{[["9.8M","Video views",Eye],["84K","Watch hours",Clock3],["4.7","Avg rating",BarChart3]].map(([a,b,I]:any)=><div key={b} className="rounded-2xl border border-white/10 bg-panel p-5"><I className="text-violet-300"/><div className="mt-4 text-3xl font-black">{a}</div><div className="text-sm text-white/40">{b}</div></div>)}</div></Section>}
