import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Mail, Lock, UserRound } from "lucide-react";
import { Button } from "../components/UI";
import { authService, getApiError } from "../services/api";
import { useStore } from "../store";

export function Auth({mode}:{mode:"login"|"register"|"forgot"|"reset"|"verify"}){
 const nav=useNavigate(); const [params]=useSearchParams(); const setUser=useStore(s=>s.setUser);
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const title={login:"Welcome back",register:"Create your account",forgot:"Reset your password",reset:"Choose a new password",verify:"Verify your email"}[mode];
 useEffect(()=>{ if(mode==="verify" && params.get("token")){ authService.verifyEmail(params.get("token")!).then(r=>setMessage(r.message)).catch(e=>setError(getApiError(e,"Invalid verification token."))); } },[mode,params]);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");setMessage("");try{
   if(mode==="login"){const data=await authService.login({email,password});setUser(data.user);nav("/");}
   else if(mode==="register"){const data=await authService.register({username:email.split("@")[0],email,password,first_name:name});setMessage(data.message);}
   else if(mode==="forgot"){const data=await authService.forgotPassword(email);setMessage(data.message);}
   else if(mode==="reset"){const data=await authService.resetPassword(params.get("token")||"",password);setMessage(data.message);}
 }catch(e){setError(getApiError(e,"Request failed."));}finally{setLoading(false);}}
 return <div className="relative grid min-h-[calc(100vh-64px)] place-items-center overflow-hidden px-4 py-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(139,92,246,.2),transparent_35%),radial-gradient(circle_at_80%_70%,rgba(34,211,238,.12),transparent_30%)]"/><div className="glass relative w-full max-w-md rounded-3xl p-7 shadow-2xl sm:p-9"><div className="mb-7 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-violet-400 to-cyan-300 text-xl font-black text-ink">S</div><h1 className="mt-5 text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-white/40">{mode==="register"?"Join a premium world of stories.":"Continue your StreamVerse journey."}</p></div>
 {message&&<div className="mb-4 rounded-xl bg-cyan-400/10 p-3 text-sm text-cyan-200">{message}</div>}{error&&<div className="mb-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{error}</div>}
 {mode==="verify"?<Button className="w-full" onClick={()=>nav("/login")}>Continue to login</Button>:<form onSubmit={submit} className="space-y-4">{mode==="register"&&<label className="block"><span className="mb-1.5 block text-xs text-white/50">Full name</span><div className="relative"><UserRound className="absolute left-3 top-3.5 text-white/25" size={17}/><input value={name} onChange={e=>setName(e.target.value)} required className="w-full rounded-xl border border-white/10 bg-white/5 px-10 py-3 outline-none" placeholder="Your name"/></div></label>}<label className="block"><span className="mb-1.5 block text-xs text-white/50">Email</span><div className="relative"><Mail className="absolute left-3 top-3.5 text-white/25" size={17}/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="w-full rounded-xl border border-white/10 bg-white/5 px-10 py-3 outline-none" placeholder="you@example.com"/></div></label>{mode!=="forgot"&&<label className="block"><span className="mb-1.5 block text-xs text-white/50">Password</span><div className="relative"><Lock className="absolute left-3 top-3.5 text-white/25" size={17}/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8} className="w-full rounded-xl border border-white/10 bg-white/5 px-10 py-3 outline-none" placeholder="••••••••"/></div></label>}<Button className="w-full">{loading?"Please wait...":mode==="login"?"Sign in":mode==="register"?"Create account":mode==="forgot"?"Send reset link":"Update password"}</Button>{mode==="login"&&<button type="button" onClick={()=>nav("/forgot-password")} className="w-full text-center text-xs text-white/45">Forgot password?</button>}<div className="text-center text-sm text-white/45">{mode==="login"?"New here? ":"Already have an account? "}<button type="button" onClick={()=>nav(mode==="login"?"/register":"/login")} className="text-violet-300">{mode==="login"?"Create account":"Sign in"}</button></div></form>}
 </div></div>
}
