import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { CalendarDays,Clock } from "lucide-react";
import { blogService } from "../services/api";
import { mapBlog } from "../apiMapper";
import { Blog } from "../types";
import { Section,Skeleton } from "../components/UI";
export function Blogs(){const nav=useNavigate();const [blogs,setBlogs]=useState<Blog[]>([]);useEffect(()=>{blogService.getBlogs().then((x:any[])=>setBlogs(x.map(mapBlog))).catch(()=>{})},[]);return <Section title="The StreamVerse Journal" subtitle="Stories, guides, reviews and ideas"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{blogs.map(b=><article key={b.id} onClick={()=>nav(`/blog/${b.slug}`)} className="group cursor-pointer overflow-hidden rounded-2xl border border-white/10 bg-panel"><img src={b.image} className="aspect-video w-full object-cover"/><div className="p-5"><div className="text-xs font-semibold text-violet-300">{b.category}</div><h2 className="mt-2 text-xl font-bold">{b.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/45">{b.excerpt}</p><div className="mt-5 flex items-center gap-4 text-xs text-white/35"><span className="flex gap-1"><CalendarDays size={13}/>{b.date}</span><span className="flex gap-1"><Clock size={13}/>{b.readTime}</span></div></div></article>)}</div>{!blogs.length&&<Skeleton className="mt-5 h-64"/>}</Section>}
export function BlogDetail(){const {slug}=useParams();const [b,setB]=useState<Blog|null>(null);useEffect(()=>{if(slug)blogService.getBlog(slug).then((x:any)=>setB(mapBlog(x)))},[slug]);if(!b)return <Section title="Loading article..."><Skeleton className="h-96"/></Section>;return <article className="mx-auto max-w-4xl px-4 py-12 lg:px-8"><img src={b.image} className="aspect-[16/8] w-full rounded-3xl object-cover"/><div className="mt-8 text-sm text-violet-300">{b.category} · {b.readTime}</div><h1 className="mt-3 text-4xl font-black sm:text-6xl">{b.title}</h1><div className="mt-4 text-sm text-white/40">By {b.author} · {b.date}</div><div className="mt-10 whitespace-pre-wrap text-lg leading-8 text-white/65">{b.content}</div><div className="mt-10 flex flex-wrap gap-2">{b.tags.map(t=><span key={t} className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/50">#{t}</span>)}</div></article>}
