import { useEffect, useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { Play, Plus, Star } from "lucide-react";
import { movieService, showService, episodeService, userService, reviewService } from "../services/api";
import { mapShow,mapContent,mapEpisode } from "../apiMapper";
import { Movie, Show, Episode } from "../types";
import { Button, Section, HorizontalRow, Skeleton } from "../components/UI";
import { useStore } from "../store";
export function Details({type}:{type:"movie"|"show"}){const {id}=useParams();const n=Number(id);const nav=useNavigate();const {myList,toggleList}=useStore();const [item,setItem]=useState<Movie|Show|null>(null);const [episodes,setEpisodes]=useState<Episode[]>([]);const [reviews,setReviews]=useState<any[]>([]);useEffect(()=>{(type==="show"?showService.getShow(n):movieService.getMovie(n)).then((x:any)=>setItem(type==="show"?mapShow(x):mapContent(x)));if(type==="show")episodeService.getEpisodes(n).then((x:any[])=>setEpisodes(x.map(mapEpisode)));reviewService.getReviews(n).then(setReviews).catch(()=>{});},[n,type]);if(!item)return <Section title="Loading..."><Skeleton className="h-[500px]"/></Section>;return <div><section className="relative min-h-[570px] overflow-hidden"><img src={item.backdrop} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/75 to-ink/10"/><div className="absolute inset-0 bg-gradient-to-t from-ink to-transparent"/><div className="relative mx-auto flex min-h-[570px] max-w-[1500px] items-end gap-8 px-4 pb-12 lg:px-8"><img src={item.poster} className="hidden h-72 w-48 rounded-2xl object-cover shadow-2xl md:block"/><div className="max-w-2xl"><div className="text-xs font-bold uppercase tracking-[.25em] text-violet-300">{type==="show"?"Series":"Feature Film"}</div><h1 className="mt-2 text-4xl font-black sm:text-6xl">{item.title}</h1><div className="mt-4 flex flex-wrap gap-3 text-sm text-white/55"><span>{item.year}</span><span>•</span><span className="flex items-center gap-1"><Star size={13} fill="currentColor"/>{item.rating}</span><span>•</span><span>{item.duration}</span></div><p className="mt-5 text-white/60">{item.description}</p><div className="mt-7 flex gap-3"><Button onClick={()=>nav(`/watch/${item.id}`)}><Play size={16} fill="currentColor"/> Watch</Button><Button variant="ghost" onClick={()=>{toggleList(item.id);userService.addToMyList(item.id).catch(()=>{})}}><Plus size={16}/> {myList.includes(item.id)?"In My List":"My List"}</Button></div></div></div></section>{type==="show"&&<Section title="Episodes"><div className="space-y-3">{episodes.map(e=><button key={e.id} onClick={()=>nav(`/watch/${item.id}?episode=${e.id}`)} className="flex w-full items-center gap-4 rounded-2xl border border-white/10 bg-panel p-4 text-left hover:bg-white/5"><img src={e.thumbnail||item.poster} className="h-20 w-32 rounded-xl object-cover"/><div><div className="text-xs text-white/40">S{e.season} · E{e.number}</div><div className="font-semibold">{e.title}</div><div className="text-sm text-white/40">{e.description}</div></div></button>)}</div></Section>}<Section title={`Reviews (${reviews.length})`}><div className="space-y-3">{reviews.map(r=><div key={r.id} className="rounded-2xl border border-white/10 bg-panel p-5"><div className="font-semibold">{r.user_name} · {r.rating}/5</div><p className="mt-2 text-sm text-white/55">{r.body}</p></div>)}</div></Section></div>}
