import { useState } from "react";
import { Section, Button } from "../components/UI";
import { liveItems } from "../data";
import { Play, Radio } from "lucide-react";
export function GenericPage({title,subtitle,form,faq,kind}:{title:string;subtitle:string;form?:boolean;faq?:boolean;kind?:string}){
 const [sent,setSent]=useState(false);
 return <Section title={title} subtitle={subtitle}>
 {kind==="live"?<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{liveItems.map(x=><article key={x.id} className="overflow-hidden rounded-2xl border border-white/10 bg-panel"><div className="relative"><img src={x.image} className="aspect-video w-full object-cover"/><span className="absolute left-3 top-3 flex items-center gap-1 rounded-full bg-red-500 px-2 py-1 text-[10px] font-bold"><Radio size={11}/> LIVE</span></div><div className="p-4"><h3 className="font-bold">{x.title}</h3><div className="mt-1 text-xs text-white/40">{x.category} · {x.viewers} viewers · starts {x.startTime}</div><Button className="mt-4 w-full"><Play size={14} fill="currentColor"/> Watch Live</Button></div></article>)}</div>:form?<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="mx-auto max-w-2xl space-y-4 rounded-3xl border border-white/10 bg-panel p-7">{["Name","Email","Subject"].map(x=><input key={x} placeholder={x} required className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/>)}<textarea required placeholder="Message" rows={7} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none"/><Button className="w-full">{sent?"Message sent":"Send message"}</Button></form>:faq?<div className="mx-auto max-w-3xl space-y-3">{["How do I change video quality?","How do profiles work?","How does billing work?","Why is a video not playing?","How do I manage my watch history?"].map(q=><details key={q} className="rounded-2xl border border-white/10 bg-panel p-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 text-sm leading-6 text-white/45">Open the relevant setting or account page. This demo includes the frontend flow and can be connected to your backend support system later.</p></details>)}</div>:<div className="rounded-3xl border border-white/10 bg-panel p-8 leading-8 text-white/55">This page is part of the complete StreamVerse frontend architecture. Connect it to your REST API, CMS or authentication provider to make the content dynamic.</div>}
 </Section>
}
